services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsLuceneBundle\OutputChannel\AutoCompleteOutputChannel:
        tags:
            - { name: 'dynamic_search.index_provider.output_channel', alias: 'lucene', type: 'autocomplete' }

    DsLuceneBundle\OutputChannel\SearchOutputChannel:
        tags:
            - { name: 'dynamic_search.index_provider.output_channel', alias: 'lucene', type: 'search' }