services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsLuceneBundle\Serializer\ZendQueryHitNormalizer:
        tags:
            - {name: 'serializer.normalizer', priority: 100 }

    DsLuceneBundle\Serializer\ZendDocumentNormalizer:
        tags:
            - {name: 'serializer.normalizer', priority: 80 }

    DsLuceneBundle\Serializer\ZendFieldNormalizer:
        tags:
            - {name: 'serializer.normalizer', priority: 60 }

